import React, { useState } from "react";

export default function Main() {
  let [inputs, setInputs] = useState([
    <input type="text" name="array[]" id="arr"></input>,
    <input type="text" name="array[]" id="arr"></input>,
  ]);
  let [FinalChoice, setFinalChoice] = useState(
    "Give us your options FATE will guide to the right choice"
  );
  function addChoice() {
    setInputs((prevState) => {
      return [
        ...prevState,
        <input type="text" name="array[]" id="arr"></input>,
      ];
    });
  }
  function addTwoChoice() {
    setInputs((prevState) => {
      return [
        ...prevState,
        <input type="text" name="array[]" id="arr"></input>,
        <input type="text" name="array[]" id="arr"></input>,
      ];
    });
  }
  function choosing() {
    var input = document.getElementsByName("array[]");
    var inputToArr = Array.from(input); // from node list to array to use map
    var mapArr = inputToArr.map((item) => {
      return item.value; // to get the value from the nodelist generated by getElementsByName
    });
    var filtered = mapArr.filter((elm) => elm.trim()); // filter the empty inputs
    if (filtered.length <= 1) {
      setFinalChoice("enter at least two choices");
    } else {
      function random_item(items) {
        return items[Math.floor(Math.random() * items.length)];
      }
      for (let i = 0; i < input.length; i++) {
        // for loop to clear all inputs after choising
        var a = input[i];
        a.value = "";
      }
      setFinalChoice(random_item(filtered));
    }
  }

  return (
    <main>
      <h1>{FinalChoice}</h1>
      <div className="inputs">{inputs}</div>
      <div className="buttons">
        <button onClick={addChoice}>+1 CHOICE</button>
        <button onClick={addTwoChoice}>+2 CHOICES</button>
        <button onClick={choosing} className="choose">
          CHOOSE
        </button>
      </div>
    </main>
  );
}
